### ISSUE TITLE
Engine revs (sound) with separator on

### ISSUE THREAD

**Issue by Szmiti** [yumi-modding/FS19_CombineXP#17]
Hello,

Great mod - thanks a lot for this ... and has a lot of possibilities to be developed further .... !  A suggestion which could make it even more realistic :-

The engine revs do not increase when turning on the separator - only when turning on the reel -> it would be much better if the engine revs go to max also when turning on the separator ?!

Thanks again !

Szmiti

**Comment by yumi-modding** [comment]
Hello
Thx for the issue.
I think today it depends on the combine. Combines that have PowerConsumer should rev up. I think it's the case for the Claas ones for ex.
Anyway, I was planning to check and add this to all combines.

**Comment by Szmiti** [comment]
Hello,

Just out of interest, experienced this with the JD T560i and MF Activa 7347S from vanilla game, as well as the Tucano 580 (from the Platinum DLC) - there _is_ a(n additional) sound when separator turned (and if you are very close to the combine) on but revs do not increase at all ....  Anyway, thanks and look forward to what you come up with ....

Szmiti

**Comment by yumi-modding** [comment]
Fixed by  807488c

**Comment by yumi-modding** [comment]
@Szmiti You can test this version at this link https://github.com/yumi-modding/FS19_CombineXP/blob/main/FS19_CombineXP.zip?raw=true Engine should revs up for any combine (at 1400rpm from what I can read with Enhanced Vehicle Mod)
