### ISSUE TITLE
Separator disabled with full tank ?

### ISSUE THREAD

**Issue by Szmiti** [yumi-modding/FS19_CombineXP#18]
Hello,

It seems the separator is disabled when the tank gets full (?) - or at least if you stop and restart with a full tank - would be nice if the separator could run with full tank - if nothing else to give the engine full revs (noise effect) ?

Szmiti

**Comment by yumi-modding** [comment]
Yes I saw that also. I'll try either to stop the cutter instead or just to display a warning and prevent to continue harvesting
