### ISSUE TITLE
Speed and engine load depending on time of the day

### ISSUE THREAD

**Issue by yumi-modding** [yumi-modding/FS19_CombineXP#19]
For each crop, add speed limit based either on Seasons Moisture or on time of the day (to mimic crop moisture effect).

![image](https://user-images.githubusercontent.com/23509583/103011996-2b7e0c00-453b-11eb-88ff-c65bbbb5a35e.png)

![image](https://user-images.githubusercontent.com/23509583/103011943-16a17880-453b-11eb-9f71-c2229b343252.png)

**Comment by Justice-Molton** [comment]
So if seasons is active, it will react on the crop moisture? because in a hot summer night you'll be able to harvest...
