### ISSUE TITLE
Forage Harvester 2km/h

### ISSUE THREAD

**Issue by Ty2k3n** [yumi-modding/FS19_CombineXP#26]
**Describe the bug**
This is not a bug just kinda a request.

I wonder if there is a way to add modded harvesters to your mod cuz I have discovered that on the John Deere 9000 from the john deere pack with ta machines that have usable monitors it just goes 2km/h but what I change to the class DLC's 980 Forage harvester it goes 10km/h so is there any way to add support for a combine.

**Comment by tdiniz93** [comment]
![fsScreen_2021_02_17_00_56_34](https://user-images.githubusercontent.com/21184284/108162981-362ccb80-70bc-11eb-9418-84aabeed2ca8.png)
![fsScreen_2021_02_17_01_02_01](https://user-images.githubusercontent.com/21184284/108162986-388f2580-70bc-11eb-95d8-8d1e249c84c3.png)

I'm having the same issue, harvesting silage corn with Seasons, 2 and 3 row headers. Crop moisture is 12.9%, yield is 14.5T/h. Pulling a New Holland FP240 with a John Deere 7810, but the same issue occurs with the New Holland 900 pull type as well.

**Comment by yumi-modding** [comment]
Hello
I will check this mod. I use vehicle category to check for forage harvester. Could you confirm you have tried with last version here on GitHub (I had no time to put it on modhub) since I'm not sure what code is actually on modhub
Thanks

**Comment by yumi-modding** [comment]
Hello,
From my tests:  John Deere 9000 is ok with standard header but I'm not able to start it with header in the pack. I don't understand why.
New Holland FP240 is put in a new shop category making my code not seeing it as a forage harvester. I don't think this mod respects Giants standards, but anyway. You can set in combineXP.xml file (in modsSettings folder, same level than mods folder) something like
`        <vehicle xmlPath="$moddir$fs19_powermoddingus_newhollandfp240/NewHollandFP900.xml" basePerf="450"/>`
and it should works better.

**Comment by Ty2k3n** [comment]
I solved it I went into the mod and edited the header and the forager categories and now it works

**Comment by MatGla94** [comment]
@Ty2k3n 

Did you just change the store categories on the Harvester and the Headers, or anything else?
