### ISSUE TITLE
Question about compability 

### ISSUE THREAD

**Issue by LawAcidFlash** [yumi-modding/FS19_CombineXP#28]
Hello yumi,

first, Thank you for your great tools.
Only a short question, is this script compatible with "Precision Farming" and "Season"?

Thank you and Best rgeards
Tobi

**Comment by yumi-modding** [comment]
Hello @LawAcidFlash 
Yes or course this mods works great with precisionFarming and season.
With PF you will notice the different yield zone during harvest (please note that display add few random to avoid having exactly the same number all the time, that was particularly true before PF came out)
With Season you will directly see crop moisture and speed will be reduced if moisture is too high.

Yumi

**Comment by LawAcidFlash** [comment]
Hello Yumi,

thank you for your reply.
Nice to hear that you have taken everything into account here.

Best regards
Tobi
